In [1]:
!pip install numpy --upgrade --quiet

In [1]:
import numpy as np

# 1D array

In [31]:
# array
%time
x=np.array([1,2,3,4])
print(x)
print(type(x))
print(x.ndim)


CPU times: total: 0 ns
Wall time: 0 ns
[1 2 3 4]
<class 'numpy.ndarray'>
1


In [20]:
# list
%time
y=[1,2,3,4]
print(y)
print(type(y))


CPU times: total: 0 ns
Wall time: 0 ns
[1, 2, 3, 4]
<class 'list'>


# Input from user

In [32]:
l=[]

for i in range (1,5):
    int_1 = int(input("enter the value:"))
    l.append(int_1)
    
print(np.array(l))


enter the value:12
enter the value:13
enter the value:14
enter the value:15
[12 13 14 15]


# 2D array

In [35]:
# 2D Array

ar2=np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


# 3D array

In [36]:
# 3d Array

ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


# Multi Dimensional array

In [39]:
#  Multi dimensional array

arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zeros

In [40]:
# Zeros

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [41]:
# Ones
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [47]:
# Empty

ar_emp = np.empty(4)
print(ar_emp)
ar_emp1 = np.empty((3,4))
print()
print(ar_emp1)
    

[7.92481296e-321 1.24610723e-306 1.29061142e-306 5.53353523e-322]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Range

In [48]:
# Range

ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diagonal

In [49]:
# Diagonal 1's

ar_diag = np.eye(3)
print(ar_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
ar_diag = np.eye(3,5)
print(ar_diag)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linespace

In [59]:
# Linspace

ar_lin = np.linspace(2,20,num=10)
print(ar_lin)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


# Random

In [61]:
# Random
# 1.rand(1D Array)

var = np.random.rand(4)
print(var)

[0.36000909 0.37930549 0.51502293 0.41900984]


In [62]:
#rand(2D array)

var1 = np.random.rand(3,4)
print(var1)

[[0.69853329 0.45941425 0.94976191 0.29730972]
 [0.11205298 0.24281478 0.60148262 0.80399553]
 [0.14383651 0.30398391 0.48022622 0.08274757]]


In [64]:
#2.randn()

var2 = np.random.randn(4)
print(var2)

[ 0.6361429   1.8516305   0.07581786 -0.06059468]


In [67]:
#3.ranf()
var3 = np.random.ranf(4)
print(var3)

[0.73156586 0.18995557 0.60667349 0.51298313]


In [2]:
# 4.randint()

var4 = np.random.randint(5,20,5)
print(var4)

[ 8 19  8 17 12]


# Data Type

In [71]:
# DATA types
#1 int
var = np.array([1,2,3,4,5,6,7,8,9,10])
print("data type:",var.dtype)

data type: int32


In [72]:
#2 float
var = np.array([1.1,2,2,3.2,4.2,5.2,6.2,7.2,8.2,9.2,10.2])
print("data type:",var.dtype)

data type: float64


In [73]:
#3 string
var = np.array(["a","b","c","d","e","f","g"])
print("data type:",var.dtype)

data type: <U1


In [74]:
#4 int & string
var = np.array(["a","b","c","d","e","f","g",1,2,3,4,5,6,7,8,9,10])
print("data type:",var.dtype)

data type: <U11


In [76]:
# How Change Data type

var = np.array([1,2,3,4,5,6,7,8,9,10],dtype = np.int8)
print("data type:",var.dtype)

data type: int8


In [77]:
var = np.array([1,2,3,4],dtype = "f")
print("data type:",var.dtype)

data type: float32


In [78]:
# How to Use data type as a Function

var = np.array([1,2,3,4])
x = np.float32(x)
print("data type:",var.dtype)
print("data type:",x.dtype)

print(var)
print(x)


data type: int32
data type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [79]:

var = np.array([1,2,3,4])
x = np.float32(var)
y = np.int_(x)
print("data type:",var.dtype)
print("data type:",x.dtype)
print("data type:",y.dtype)


print(var)
print(x)
print(y)

data type: int32
data type: float32
data type: int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [81]:
# Change data type Using astype function
a= np.array([1,2,3,4])
b= a.astype (float)
print("data type:",a.dtype)
print("data type:",b.dtype)

print(a)
print(b)

data type: int32
data type: float64
[1 2 3 4]
[1. 2. 3. 4.]


# Arithmatic Opratins

In [88]:
# Arithmatic Opratins
# 1D
# 1. Adddition

var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [96]:
# Addition Using np.add(a,b) function

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [97]:
# Addition Using np.add(a,b) function

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1,3)
print(varadd)

[4 5 6 7]


In [89]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1+var2
print(varadd)

[2 4 6 8]


In [90]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1-var2
print(varadd)

[0 0 0 0]


In [91]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1*var2
print(varadd)

[ 1  4  9 16]


In [92]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1/var2
print(varadd)

[1. 1. 1. 1.]


In [93]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1%var2
print(varadd)

[0 0 0 0]


In [94]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1**var2
print(varadd)

[  1   4  27 256]


In [95]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1//var2
print(varadd)

[1 1 1 1]


In [99]:
# 2D array

# Addition 

var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
varadd = var1+var2
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [100]:
# 2D array

# Addition usinf np.add(a,b) function

var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
varadd = np.add(var1,var2)
print(varadd

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [101]:

var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
varadd = var1*var2
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [102]:
# 2D array


var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
varadd = var1-var2
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[0 0 0 0]
 [0 0 0 0]]


In [103]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
varadd = var1/var2
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [104]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
varadd = var1**var2
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[  1   4  27 256]
 [  1   4  27 256]]


# Arithmatic functon 

In [105]:
# Arithmatic functon 
# 1. min & max

var = np.array([1,2,3,4,5,8,5,3])

print("min :",np.min(var))
print("max :",np.max(var))

min : 1
max : 8


In [106]:
# 2. argmin & argmax : to find index position of array

var = np.array([1,2,3,4,5,8,5,3])

print("min :",np.argmin(var))
print("max :",np.argmax(var))

min : 0
max : 5


In [113]:
# 3. To find  axis

var = np.array([[2,1,3],[9,5,6]])

print(np.min(var,axis=1))


[1 5]


In [114]:
var = np.array([[2,1,3],[9,5,6]])

print(np.max(var,axis=0))


[9 5 6]


In [115]:
# 3. sqrt


var = np.array([1,2,3,4,5,8,5,3])

print("min :",np.argmin(var))
print("max :",np.argmax(var))
print("sqrt:",np.sqrt(var))

min : 0
max : 5
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798 2.82842712
 2.23606798 1.73205081]


In [117]:
# 4. Sin & cos


var = np.array([1,2,3])

print("sin:",np.sin(var))
print("cos:",np.cos(var))

sin: [0.84147098 0.90929743 0.14112001]
cos: [ 0.54030231 -0.41614684 -0.9899925 ]


In [119]:
# 5. cumsum

var = np.array([1,2,3,4])
print(np.cumsum(var))

[ 1  3  6 10]


# Shape & Reshape

In [120]:
# Shape & Reshape

var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


In [121]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


In [123]:
# Reshape

var = np.array([1,2,3,4,5,6])
print(var)
print(var.ndim)
print()
x = var.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [128]:

var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x = var.reshape(2,3,2)
print(x)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [130]:
# 3D TO 1D


var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x = var.reshape(2,3,2)
print(x)

one = x.reshape(-1)
print(one)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [134]:
# Broadcasting array

var1 = np.array ([1,2,3])
print(var1.shape)
print(var1)

print()


var2 = np.array([[1],[2],[3]])
print(var2.shape)
print(var2)

print(var1+var2)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [136]:
var1 = np.array ([[1],[2]])
print(var1.shape)



var2 = np.array([[1,2,3],[1,2,3]])
print(var2.shape)

print(var1+var2)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


# Indexing

In [4]:
# Indexing
# 1D:

var = np.array ([9,8,7,6])
# Positive 
print(var[2]) 
print()
# Negative
print(var[-3])

7

8


In [9]:
# 2D:

var =  np.array ([[9,8,7],[4,5,6]])
print(var)
print(var.ndim)
print()

print(var[0,2])
print()

print(var[1,2])



[[9 8 7]
 [4 5 6]]
2

7

6


In [14]:
# 3D:

var =  np.array ([[[1,2],[1,2]]])
print(var)
print(var.ndim)
print()

print(var[0,1,1])
print()

print(var[0,0,0])


[[[1 2]
  [1 2]]]
3

2

1


# Slicing

In [23]:
# Slicing
# 1D:

var = np.array([9,8,7,6,5,4,3])
print(var)
print()

print("8 to 5 :",var[1:5])

print("8 to end :",var[1:])

print("Start to 5 :",var[:5])

print("Stop :",var[::2])

print("stop :",var[1:5:2])

print("stop :",var[1:6:2])

[9 8 7 6 5 4 3]

8 to 5 : [8 7 6 5]
8 to end : [8 7 6 5 4 3]
Start to 5 : [9 8 7 6 5]
Stop : [9 7 5 3]
stop : [8 6]
stop : [8 6 4]


In [32]:
# 2D:

var = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var)
print(var.ndim)
print()

print("8 to 5 :", var[1,1:])
print("12 to 15 :",var[2,1:])
print("2 to 5 :",var[0,1:])


[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
2

8 to 5 : [8 7 6 5]
12 to 15 : [12 13 14 15]
2 to 5 : [2 3 4 5]


# Iterating

In [34]:
# Iterating
# 1D:

var = np.array([9,8,7,6,5,4])
print(var)
print(var.ndim)
print()

for i in var:
    print(i)

[9 8 7 6 5 4]
1

9
8
7
6
5
4


In [35]:
# 2D:

var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print(var.ndim)
print()

for j in var:
    print(j)
print()

for k in var:
    for l in k:
        print(l)
    

[[1 2 3 4]
 [1 2 3 4]]
2

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [37]:
# 3D:

var = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var)
print(var.ndim)
print()

for j in var:
    print(j)
print()

for k in var:
    for l in k:
        for m in l:
            print(m)
            
       
    

[[[1 2 3 4]
  [1 2 3 4]]]
3

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [39]:
# Iterating using np.nditer function
# 3D


var = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var)
print(var.ndim)
print()

for i in np.nditer(var):
    print(i)
            


[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [43]:
# How to change data type in Iterating
# 3D: int to String

var = np.array([[[1,2,3,4],[9,8,7,6]]])
print(var)
print(var.ndim)
print()

for i in np.nditer(var,flags=['buffered'],op_dtypes=["S"]):
    print(i)
            

[[[1 2 3 4]
  [9 8 7 6]]]
3

b'1'
b'2'
b'3'
b'4'
b'9'
b'8'
b'7'
b'6'


In [46]:
var = np.array([[[1,2,3,4],[9,8,7,6]]])
print(var)
print(var.ndim)
print()

for i in np.nditer(var,flags=['buffered'],op_dtypes=["i"]):
    print(i)

[[[1 2 3 4]
  [9 8 7 6]]]
3

1
2
3
4
9
8
7
6


In [47]:
# Iterating With Indexing using np.ndenumerate function

var = np.array([[[1,2,3,4],[9,8,7,6]]])
print(var)
print(var.ndim)
print()

for i,d in np.ndenumerate(var):
    print(i,d)

[[[1 2 3 4]
  [9 8 7 6]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 9
(0, 1, 1) 8
(0, 1, 2) 7
(0, 1, 3) 6


# copy vs view

In [48]:
# copy vs view
# copy

var = np.array([1,2,3,4])
cop = var.copy()
print(var)
print(cop)

[1 2 3 4]
[1 2 3 4]


In [51]:
# view

x = np.array([1,2,3,4])
vi = x.view()
print(x)
print(vi)

[1 2 3 4]
[1 2 3 4]


In [50]:
# copy:values not changed 

var = np.array([1,2,3,4])
cop = var.copy()
var[1]=12
print(var)
print(cop)

[ 1 12  3  4]
[1 2 3 4]


In [52]:
# view: changed values

x = np.array([1,2,3,4])
vi = x.view()
x[1]=12
print(x)
print(vi)

[ 1 12  3  4]
[ 1 12  3  4]


# Join and Split 

In [54]:
# Join and Split 
# 1D

x = np.array([1,2,3,4])
y = np.array([9,8,7,6])
z = np.concatenate((x,y))
print(z)

[1 2 3 4 9 8 7 6]


In [55]:
# 2D

x = np.array([[1,2],[3,4]])
y = np.array([[9,8],[7,6]])
z = np.concatenate((x,y),axis=0)
print(z)


[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [56]:
x = np.array([[1,2],[3,4]])
y = np.array([[9,8],[7,6]])
z = np.concatenate((x,y),axis=1)
print(z)


[[1 2 9 8]
 [3 4 7 6]]


In [57]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])
z = np.stack((x,y),axis=1)
print(z)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [58]:
x = np.array([[1,2],[3,4]])
y = np.array([[9,8],[7,6]])
z = np.stack((x,y),axis=0)
print(z)


[[[1 2]
  [3 4]]

 [[9 8]
  [7 6]]]


In [59]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])
z = np.hstack((x,y)) #row
print(z)

[1 2 3 4 9 8 7 6]


In [60]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])
z = np.vstack((x,y))  #column
print(z)

[[1 2 3 4]
 [9 8 7 6]]


In [61]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])
z = np.dstack((x,y)) #hight
print(z)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [66]:
# Spilt 
# 1D
var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,3)

print(ar)


print(ar[0])
print(ar[1])
print(ar[2])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [69]:
# 2D
var = np.array([[1,2],[3,4],[5,6]])

print(var)

ar = np.array_split(var,3)
ar1 = np.array_split(var,3,axis=1)


print(ar)
print(ar1)


print(ar[0])
print(ar[1])
print(ar[2])

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
[[1 2]]
[[3 4]]
[[5 6]]


# Nupy Array Functions

In [4]:
# Nupy Array Functions
# 1. where

var = np.array([1,2,3,4,2,5,2,5,6,7])
x = np.where(var==2)
print(x)

(array([1, 4, 6], dtype=int64),)


In [5]:

var = np.array([1,2,3,4,2,5,2,5,6,7])
x = np.where((var%2==0))
print(x)

(array([1, 3, 4, 6, 8], dtype=int64),)


In [7]:
# 2. Searchsorted

var = np.array([1,2,3,4,6,7,8])
x = np.searchsorted(var,5)
print(x)

4


In [8]:

var = np.array([1,2,3,4,6,7,8])
x = np.searchsorted(var,5,side="right")
print(x)

4


In [10]:

var = np.array([1,2,3,4,6,7,9])
x = np.searchsorted(var,[5,8,10],side="right")
print(x)

[4 6 7]


In [11]:
# 3. Sort array

var = np.array([1,2,3,4,12,5,22,25,6,7])
x = np.sort(var)
print(x)

[ 1  2  3  4  5  6  7 12 22 25]


In [12]:
var = np.array([[1,2,3],[4,12,5],[22,25,6]])
x = np.sort(var)
print(x)

[[ 1  2  3]
 [ 4  5 12]
 [ 6 22 25]]


In [13]:
var = np.array(["z","l","n","a","y"])
x = np.sort(var)
print(x)

['a' 'l' 'n' 'y' 'z']


In [16]:
# Filter array

var = np.array(["n","i","k","h","i","l"])
f = [True,False,True,True,False,True]
new_a = var[f]
print(new_a)


['n' 'k' 'h' 'l']


In [19]:
# Shuffle

var = np.array([1,2,3,4,6,7,8])
np.random.shuffle(var)
print(var)


[4 8 6 7 3 1 2]


In [20]:
# Unique

var = np.array([1,2,3,4,2,3,4,2,6,7,8])
x = np.unique(var)
print(x)

[1 2 3 4 6 7 8]


In [22]:
var = np.array([1,2,3,4,2,3,4,2,6,7,8])
x = np.unique(var,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 6, 7, 8]), array([ 0,  1,  2,  3,  8,  9, 10], dtype=int64), array([1, 3, 2, 2, 1, 1, 1], dtype=int64))


In [24]:
# Resize
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(2,3))
print(x)

[[1 2 3]
 [4 5 6]]


In [27]:
var = np.array([[1,2],[3,4],[5,6]])
x = np.resize(var,(3,2))
print(x)

[[1 2]
 [3 4]
 [5 6]]


# Flatten: convert 1D to 2D and 2D to 1D

In [28]:
# Flatten: convert 1D to 2D and 2D to 1D


var = np.array([1,2,3,4,5,6])
x = np.resize(var,(2,3))
print(x)
print(x.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [29]:
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(2,3))
print(x)
print(x.flatten(order="F"))

[[1 2 3]
 [4 5 6]]
[1 4 2 5 3 6]


In [30]:
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(2,3))
print(x)
print(x.flatten(order="C"))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [31]:
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(2,3))
print(x)
print(x.flatten(order="A"))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [32]:
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(2,3))
print(x)
print(x.flatten(order="K"))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [34]:
# Ravel
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(3,2))
print(x)
print(x.flatten(order="C"))
print(np.ravel(x,order="F"))


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 3 5 2 4 6]


# Insert

In [36]:
# Insert

var = np.array([1,2,3,4,5,6])
print(var)

x = np.insert(var,(2,4),40)
print(x)

[1 2 3 4 5 6]
[ 1  2 40  3  4 40  5  6]


In [37]:

var = np.array([1,2,3,4,5,6])
print(var)

x = np.insert(var,2,40)
print(x)

[1 2 3 4 5 6]
[ 1  2 40  3  4  5  6]


In [39]:

var = np.array([[1,2,3],[4,5,6]])


x = np.insert(var,2,7,axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [7 7 7]]


In [40]:

var = np.array([[1,2,3],[4,5,6]])


x = np.insert(var,2,7,axis=1)
print(x)

[[1 2 7 3]
 [4 5 7 6]]


In [42]:

var = np.array([[1,2,3],[4,5,6]])


x = np.insert(var,2,[11,12],axis=1)
print(x)

[[ 1  2 11  3]
 [ 4  5 12  6]]


In [43]:
var = np.array([[1,2,3],[4,5,6]])


x = np.insert(var,2,[11,12,13],axis=0)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]]


# Append

In [48]:
# Append

var = np.array([[1,2,3],[4,5,6]])


x = np.append(var,[[11,12,13]],axis=0)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]]


# Delete

In [49]:
# Delete

var = np.array([1,2,3,4,5,6])
print(var)

x = np.delete(var,2)
print(x)


[1 2 3 4 5 6]
[1 2 4 5 6]
